// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnevezuhdqyoaiywzjbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZXZlenVoZHF5b2FpeXd6amJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDQ2NzIsImV4cCI6MjA3MTY4MDY3Mn0.J9RYMgPQlCskbPHFI9L3nhreK-Sw42kwjxQIbnsUT70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});